jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd backend
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
         secure: ui7q9vJGNXjUGNxIuIIu+Wj7axgMSbb8DkcL6JnN0c1EtaqqHg4tAR68xJa7vVm6Ifft6k/9NbWmBHoSe3QVxdJNz2aqBt2Cdnnoc0GdxgVT6YO6JjEjtxk+sFvoMIM/r0ezYsDlBsZo9LmbuTftjTjtOpRADgi6GupymxFcf7R8BFkx91I5JsS7G3jeNQWykcsSLO9i3803gB2+u9BQbSv+pk5QKTb7cxGz3mhoUbPxHKgztPOgkeeAa32lM6bGivF6Ht4AasfSVrDARe9da1cqqDNr27wRaT+8kpfjfHVqho77MceDPOXeFObM4IATs3pcfb+4CQo6sJYKXpx9QEab4TtYLrWb3g7s/Tg/zo1ltStAACC9r0w8gT0JURAulo3fAFIbqZRZPSPrZ36YZsiMmIu7C6jiGSJ+9Elp5QzdGCT8JItzsNZvv0PuK897B83evmGGPzCjEK27bo1I1IF6alwfk9QrW5pehGSPVLFsTAvdJ9mOQqHQ3hzRwhLOmACJHwRB0DKGj5l27jdxMWYZvZK/XJ3Q9Ml4hTSc0aluXoU345/B/8n7w6/XiAIgnj0UDFLcp9yG1icsumq3GgolMA03bZ5CGUoWjb6iC0ClIcabuLime+HSz54HpD66mNtre3JXddaLPiQpSDOqyLJj0xLR6g3T9pmhW+O+qiU=
         app: languagelearningapp
      on: main

  - language: node_js
  
  
    node_js: node
    
    cache:
      directories:
        - node_modules
        
    branches:
      only:
      - master
      
    before_install:
    - cd frontend
    
    before_script:
    - npm install -g @angular/cli

    script:
    - ng build --prod --base-href [base_url]
  
    deploy:
      skip_cleanup: true
      provider: heroku
      local_dir: dist/frontend
      api_key:
         secure: ui7q9vJGNXjUGNxIuIIu+Wj7axgMSbb8DkcL6JnN0c1EtaqqHg4tAR68xJa7vVm6Ifft6k/9NbWmBHoSe3QVxdJNz2aqBt2Cdnnoc0GdxgVT6YO6JjEjtxk+sFvoMIM/r0ezYsDlBsZo9LmbuTftjTjtOpRADgi6GupymxFcf7R8BFkx91I5JsS7G3jeNQWykcsSLO9i3803gB2+u9BQbSv+pk5QKTb7cxGz3mhoUbPxHKgztPOgkeeAa32lM6bGivF6Ht4AasfSVrDARe9da1cqqDNr27wRaT+8kpfjfHVqho77MceDPOXeFObM4IATs3pcfb+4CQo6sJYKXpx9QEab4TtYLrWb3g7s/Tg/zo1ltStAACC9r0w8gT0JURAulo3fAFIbqZRZPSPrZ36YZsiMmIu7C6jiGSJ+9Elp5QzdGCT8JItzsNZvv0PuK897B83evmGGPzCjEK27bo1I1IF6alwfk9QrW5pehGSPVLFsTAvdJ9mOQqHQ3hzRwhLOmACJHwRB0DKGj5l27jdxMWYZvZK/XJ3Q9Ml4hTSc0aluXoU345/B/8n7w6/XiAIgnj0UDFLcp9yG1icsumq3GgolMA03bZ5CGUoWjb6iC0ClIcabuLime+HSz54HpD66mNtre3JXddaLPiQpSDOqyLJj0xLR6g3T9pmhW+O+qiU=
         app: languagelearningfrontend
      on: main