jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "eltiRR9//gn4JB0yCGLN2fnD5cgOIgyyESDJrIgJ0qtE8nWPdxiz9pSK4VDuRARE6+4Ujx6I17KarD7bWBe1hhwbabhx57QATtwcLgIgIoxDK9hXDVYwXr6izbrFDsoV1Pdli1JIZs87oxoWWZGG2rbicCbnlUaDFHItpH5FgTpbNzxxoCtdDhROjfE8hJJgurkDVtLuAxdy3ubPyL3bhZnqC3xP6rlR2+l/58S39prmk/IuMDZIz/Ju4Q5EyqDPsAEkdngzP81Q9udm+TTnvDa4tjn/vbgnHY9aHyEM28llIGAsoUdDSvMVSBirdm7/ewg0tlp+QfQ0qQlYc6frMBVqAcXbS2iOIDEkc70acm3tU+ETQQXci48pY+xdP8FC1jVSExY5ibVN8jt0fglN8Iz9xpDND+xMaTbMD/Nj//fpYRQrG4uyrM4qO9/qsVP0eJeAyZgW95lLTnypr7gZ9W4nrx/DNOHBFlr6v2m71ecxuLKpuXQPgLONfxpIvI+1NDGkI/7UoIJpmTndHxHIZM17rR3YQ8CncgJg/a5z60w3+k9KEKooc7KURbNQziqnTY4okkFbbMJErwhIcQW5ClzViO1d8ME/lHBhumy98QkOvXefY8thNFSYVktTgio+uWKnFRWY57YkhUE+D90DWTpGuEBMgqqZaLPXhEkr78g="
      on: main