jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "k4ZttyRyQXpMvz+szorGXEy4VPAF1ddV9td/ptQ813G6ictQBAAIZIPkHqImUGxouredlakmAm9JKvADdqgSFw+vPddOCA+Qx7O/j2J7/oazHEgbdI8rBJNhxbm4uU7k0hjobaJDrNaOb3XWpbDBp0KZ+17IUrRRs8qNgQhLTSOKLQVgIPWpN67X+po9LfeMCXynydUO7u15CsVUPqzNz/x0r4TNR6lU4tNe1hmcGiPeLRxK8c4kDEqBuRNOzwsBs2sskFdIWShJzkaOUeUhz4S9ecxnw5/yLLudbnkFkKC5WAK0vI+WyQL+EFpvpfwDLQWkFPNIy6IsN4DYHj5I/XrxT6V1E7sEVN3Gxia17f4fGiinUZfUwWSu3R4Tlj9KGQ5xeS3clmn7GA2xHpHqZ7X9WHOMKSrrI0RjHnA020TkfKYN2AuTDUMTXGQe9BOJ7hGuDpIGL3kbYF9hGHpr4CcD5t2OSUcMk0jxewAvcGEyW8wUV6FpnZ615PsFpGBx5u+9cnkOfsV+vRH64CApxvfOeXXIJSl5t+yHC9zkHbDKiriscGhm2R3PvZXhsngQqY4RHqu2PiJw0LPpqef0M13qcU3lDakCXXYeXcPZne98ho6q2osdP7OIhtJO0P/tqpa06FTeUuJuAW3l6tGyVaOmQMjaATzFJiZ/9wrQ6Hk="
      on: main