jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd backend
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
         secure: iwjamZK4kQakfWK7CA7IQOyqL2EPSUHeOYZH9R/X+NRMIhXTY3b6KbtTRfvm6Mh5PCkMsfbZMOvuRzRzhhPsJUO4NtAgYIxu6EFybKYeGaVElkip0fXoCPCraVkguMP5/Y3VkeS+8XQrz7UvsNCBoIcRhPKJG8pRkD0Pc8M+PIgmxjIoQ5GQkLPFRHGNj5pPWVOx8mmF+lYhV2Y/FGuWZInRHjWQXN3M9IPFLHJlFZ9tzUGcea5p9e/H4D22BSFtwDATy2n4/W2tC74cwTWoVx8iDvuspEgcDTTsh4dQhGZs4uBAmOKEFXPF2UNHjP3zJu1VXx6fpyNRU0GI4C37fd4Nzg83qolDYt+VrNG6QoF/8OQmbWbKy6iMkPc5K2YGgGFA0Dv490DU0f/RRLoBF8K8Gv9DgkONGEnEoPsssVBkh3ewgHWaw6ZuY4Rp9CZJNk+5JfFvtpePgjs1VOrjhQQmoGfaaDDUf7wTf8iVHaukxrCR90ujAEuMzanItBfXkHnXYmgCXoVT2Jj87LkEFIzMFjRAbcXjfC+siTl2XYQT4zr9lfy8I0zvQkGt0TkOoAs8Nwz1df/rJXMnFUOMjFvEahi9+XEWhProB/T4EpOcr2804SwfnWtc8Z/r0f14d/0CXdNauSqXYkfWyVXEDRGzfCn0vTRlp64yYmugIBQ=
         app: languagelearningapp
      on: main

  - language: node_js
  
  
    node_js: node
    
    cache:
      directories:
        - node_modules
        
    branches:
      only:
      - master
      
    before_install:
    - cd frontend
    
    before_script:
    - npm install -g @angular/cli

    script:
    - ng lint
    - npm run test-headless
    - ng build --prod --base-href [base_url]
  
    deploy:
      skip_cleanup: true
      provider: heroku
      local_dir: dist/frontend
      api_key:
         secure: iwjamZK4kQakfWK7CA7IQOyqL2EPSUHeOYZH9R/X+NRMIhXTY3b6KbtTRfvm6Mh5PCkMsfbZMOvuRzRzhhPsJUO4NtAgYIxu6EFybKYeGaVElkip0fXoCPCraVkguMP5/Y3VkeS+8XQrz7UvsNCBoIcRhPKJG8pRkD0Pc8M+PIgmxjIoQ5GQkLPFRHGNj5pPWVOx8mmF+lYhV2Y/FGuWZInRHjWQXN3M9IPFLHJlFZ9tzUGcea5p9e/H4D22BSFtwDATy2n4/W2tC74cwTWoVx8iDvuspEgcDTTsh4dQhGZs4uBAmOKEFXPF2UNHjP3zJu1VXx6fpyNRU0GI4C37fd4Nzg83qolDYt+VrNG6QoF/8OQmbWbKy6iMkPc5K2YGgGFA0Dv490DU0f/RRLoBF8K8Gv9DgkONGEnEoPsssVBkh3ewgHWaw6ZuY4Rp9CZJNk+5JfFvtpePgjs1VOrjhQQmoGfaaDDUf7wTf8iVHaukxrCR90ujAEuMzanItBfXkHnXYmgCXoVT2Jj87LkEFIzMFjRAbcXjfC+siTl2XYQT4zr9lfy8I0zvQkGt0TkOoAs8Nwz1df/rJXMnFUOMjFvEahi9+XEWhProB/T4EpOcr2804SwfnWtc8Z/r0f14d/0CXdNauSqXYkfWyVXEDRGzfCn0vTRlp64yYmugIBQ=
         app: languagelearningfrontend
      on: main