jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "wi1zOww9v9irY6Y0cdoayE+uoBn6yWE7fnHRKTXntgEEVbII5MF2Y4M7tCH/Da3wSStwrMd9wNKrQK5Qz/Rok3aUoq/OsWVba3VEv+SAFG268RV0YpJdO0xZQnyVbA6KGbRWJu/t+QpgJq5UCRElVQ3ZQCoKDra1cqvhwImojU8lWndTl+53GLiLtJ4FYp95p1xDelkb45VFeFv3Dys7LJV6nnGC4XvG9NG48q2bZT1bIT80OgJCAeJwrnm3xv6vpR9Tp2Huh4dE7R6612oPE2yDablzb0PpMi9E7hp18dfYZNYowBpE7TWyZm+3fb/UNnMKkgHOGm5gAM6QLOHGsMF2HmQYizxlK3+4wUc5Teq8puhjxnNLTWbih2+XBgLuRCD79j+8XWzb4jhg5OWbWawlf2FfPse+7cbT03MYvKvdWls1yLmy1N+1LmasR94r6vwBWN5qMb1rR5Vg2gWiY2L5wVqt65EuFbq3uASWA7Hc9ibSoSfUyGQvU8tjmBVPcFnPz65MpMj9G1xOI+8r3aHq9GGT5QaBakAeRoboVCqYtUFV9zKWA5X273xOJQ2VRHAOHa89gqQsLsODcXSpfo4MlPsgbDmE9l+jSAcI/Wr1Qltt32f2vjb7Kibk3lUgfz/GGMhdpZjxsvwshHx8TMNTMA6Viwz7g/WDnrNXaD0="  
  app: languagelearningappbackend
  on: main

