jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "T+FdRpxFeBURCL45MpxcaVhT55zqHU14jrC1OqTQ/p2JNaDBUAFYUtpASlpAXhTm7XSYZJ0LYX0Ib5zgDvwRwJX5r3LlGTF2LSWPdhi7zfvKbC8uC72nxjleK4DaGupcXTdLEK3Oi+S5i34qSSLr8FCqYa1DP7Yon0sGStlLlUrdstzVRH8s55n20J0BnbmaFoyrAMLtQw3GzZw4iD6iNwNAzlmSv4WOhe8ATDeb6wHFrdhSf7tfWP+mHtKU9TY3NzC0ucyqNOrpyd2eXAhlPDuUTXOM+KQTTmK7d4DD4qwpTtU8LgXaabQTnTjPTkbwE4wohb+E6oBHEjzMLIaQqeAvLVLxvgYHt32j/p1CSXuhC7Vxm60SnxxkzgQcjC+ZCPKb8h0kxc5Ig2MCQ99ERVMxys/9vmdutJDVGHrA+sH4bqCRjsgiOhsnzWffLd6ai9cfO0mYOoleUUJkTHftykO7jq31HxuiVJ3sDRaTxKuOyY4fytZTvHSwM5W159ORH7Fh+9ur9XyeiTuJ/UDLxzL1iphRU6YNcSN3nDrH99vxL3lghkPQ5060/NN/7dNsRyGxdz1yx+29q8vFDIVy0Y2Zf6/DcPTZp+sxlD0Jpr2vKXQ+JshQ14TU6tOupW3Pft93WXROhs4sGWZDAZzjHcfjf4QlfJoAXtjRbOpZFbU="
      on: main