jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    before_install: cd backend
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "B629MRw2dW2287X6BOJGAF7VrpjN8uvBwKbCetc7KzNc0sQmQ6allS6qwNHshgT1kXpNReRpC1dG4ExlIf6YaLTcq4Xhhoat3sEaEaMEVsW5gXShqFFkXu0DccHUhuYYX775e1JfEFviC2lWLPV0JB3bmIg51SbxJ1D1eOEXSXbYfzBl+qo2Kkpi0ob7Oq80TjJCUPotOj9o1xOAsYdQy6C+K7uRqNIJrSESGAUMvv7FmqgQSqJ63ETwdFeLzAToDvaR3/mKpnbJn1pWZIo4CfBoCq/8LZUyy3mtCQq39wHa9kGCRsgaiNXt+KlPRadNgteL6G/gjJpB9I7yHOJtiSwwNhAgQ0YblUiOwYX+v2R/gp+vlVnye7jFhfL4wXsOtZ4PBurYO5kimsYxFbhYlW3ZP4NyiTazgAOGD/8cccIY9SaOuTEQN+wFj4mmc2wAtF0jNZ0wesMtHmtYBNf5eDpoCUtNOhpgTP3+ysr5TKWaCXsb2I9Id4SfUn4Sm0cFBDS8k92jEQoM1Vec43SSNmVxCL91cPT+4yMdirL/luici4taldEcs2bbEDN7+A7DCDTXDWU4EsJDFgAxoDrFD3q0acNzLwckaAhrChGmpjc/42zdN27Ch060x5FnYhLhlOHzFIpwYBk09T0E8hkefANCwNu6wD6w/jCtTN+b5W0="
      app: languagelearningappbackend
      on: main