jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    before_install: cd frontend
    before_script:
    - npm install -g @angular/cli
    script:
    - ng build --prod
    deploy:
      skip_cleanup: true
      provider: heroku
      local_dir: dist/frontend
      api_key:
        secure: "SlrHvJ7usRsorb8/g/xnDDzyyhSw/9BtR0sj2IrRrO1+NYgpXPc1rf4ak69DRgrnQWY6pLMU5Ir40YangU77URc1fKUHXNC9K6mQuxTyjFcyoQBrPnqB4z1eKZDCiu8iA5FVqN2jX8yFbOwMnCNud9ixIauB/i0DWkqM7HHpWlLniY/sKH6c6EakbVSOY0oH1nxwc9lmO+hYEVCFndutZVYSSHSQhI6GdLLWvUK5smgxVaCNs5apwDDan+1C2WquIiBG5kiD5p9ljVbf77+CMZJ08hlh6M29Hz1v70Ra3+IIYNOAuaZqaUGsBV+uLLYaSfatrtK8edOU403lsgXJMvbShD/UnvECark38Zp6FGl0f0drsmUR2CA3aVmhtngNku5qbXSZ4YS14Xnnrbq5czbray7XQvhqTQIGf4Y6uTL6NUPzQiub+XOc/OUYnSOEggZ/dSBbn35Rwmcl0bzbSmDVJqBczPSn06h2dAKdBhbBDfADyN8NrhZXkYEnqGAVBhPh4fEbNXrud7AGWhYtb2y1OHvGqg6fQl+8OdguQHonajA/RVul3b6jslVplsUCX54SnTwr+haehC+T3M6ptRwn/mLq6DmjiHaXuxyCjiJT6SZA7A+Q301vJegRsYTbLmVV+skGr+nqxVOXr7+EgwPiEJMcos/4au+FDVx9ZkQ="
      app: languagelearningappfrontend
      on: frontend