jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "EVXUSSASDyEFNAZAN+5jWUhIZid+ukDQldIVdVARrI/1FGT8M9ZV9Ed1E5dLTXvCfw5R12Q2L08hSNmbVG/MBpA/kfbxlAfuicKUTF05Ez+fcJ34B8qQbk/kzWTKhMkL1uXBh2AjfPLNq7xZqIMraj/rcFPhC1BiRUHD0LToyOXLGXbnwqtHyickEkI58LuB9z2pnpzq3lVEDkZWHgi0loCSxSGViQnfBfxRCz/uoR9CvMThunouCwOdX4mg/PnIps12L72kjV2G8jRBNhpUDoOjlYCtDl4NbtwhpiwXYHgHFhGwTSHpkcKWik/CWRRaZVJ3r5gXoBC56J6YWM/YcZnOOadGqMHBLqRaikdb9NQpf8LQmSmVJdLolaXBqZrgPieCGOcv0db/FEnrVl72+zKB/a0xzSqW7peJnFEOPcV5LqST81T+XrWQgNgHOUo1thbbV6HV8JfV/53VKg5gdLDRsT8hJG3Sc9mSBMFTw6TD9zU9EeUQFJBZki5UgcnEZH5aGxfQskO9+3x1DeZn/oojFa+obElzC3F7owP4/NNtvgK+yT3DOSSMK7dhMGU3YgfyVPcypj6gJ5Agkl6J5PezkUT1ttTnXbeXK4cxyoN84fHwd8WqGpSERh3XcWdm9Weg+y7He+GfMATmu5m3I9fX9h8L1JUXE+VCYX/OGFw="
      app: languagelearningapp
      on: main