jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "fRv1RmMi8gCf96zH474N6KM2wvAfp/PaTmHf0+gBfvG3rT+lS60ePeZQTgHMkA6nfbsJ+Cst9AnAXLYZQFfteHNsGIdgkae9+8XaCVIWLYQWuRFL6Js2NAA3/DJ/B8TIq2ljuS+1NMnc4kHbcFFyq4wzwntQkp9eJdmJcQD4cyXnOE47TYWxMw25PPexP+SrFfR1y/h6pgKp0AreZP4N+pAcF2K/gAjGBiKIyA4VHNTeMtCKWpRcl2aCvOhtAB0m2zA9mnYgxjf8yLu+yLa+Z1ngkpSk7jlFX/BWHiAg8K9lD5A9nMu1U4CcoXeUvlaypPdWpLiAW4vfYles/2b6YHsyNLcbQQdrJcJHjEc5YtokHnmKUaKBpKEdldXoao0o8951WLCUuOZIu9OLShYnPZ/qKleoZ7zx3OtiRM2bGkIRJVyDI/YdPdF2XPi3i2+1kPvCQNgvLTIcCAhZFPfd8Mn6DOBlCd7PL55Rj3NVsiKoNceM67n/JUg52LoxMX7VSOP1dBrQkZTmxx1fYbiuVGZAXjn4tpH3EUBamxPX4ZT0M0vRCuPpvdfFvsn0GEQv6ze10MbZSoRgxpypl3UZJ3AwvOxnNJWMSbgpPPf0HmLZze7jMpq/ZWydP+k0nB/MXuO6+UVmiB7zR3DKeBoWdRdKNp91Pkjb8dFfPXk2Nqk="
    app: languagelearningappbackend
  on: main

