jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: XPfVyMZZo5/43IDGmgSDyUumf8MH9oDyb/a1ob8SOXw8mTmaVMKrCWKD0jXrJRKBYVCFZACJWEzPz6LBDV+VhNsND9TxBMqmPIZUuPE0kiW37hVAl0TxR0ycNCP5iNK0EZnRtCPjo61EP2JUEHT6XfrPFaxCLhvy6pndCLgGC9BmKbQje0JkCEJoP+9X/k28d+FQ/dWwVZqlTn81zobnnQZA7En2CmRj8M2YhyWqyAbtIrD2jpsO5zWHoV7HELg+SX56CDGqQ4KnC005UiK5xMV/MSoo5UGev85A4hLorRZQyJ1EEZM2ByCMXTPMtVSd+TKRHKQBlLWB8bJc+Z4zTUHx2YBsWC+vKKPvr3guRpU812kcJB0lABwBqb0w7H6FOIAUwbK3mpiu2qfVOiVvEEGX/BgRgCDfgWtuG7A4oANyfPkthTMjYCGwczEpUhlY/STwK3clwGSD+Go2Y5HBHmwe30VeqFbZVZOnv/kASN/Bld5U2olbAsBWqG6HCLINZic3erQnqxzaR+c4gRhFtJzagDeSC+Qk5HxbOWRqqqfx8ReS9ZmHGR2sglyrNbGp3sSAaCVfkMvx3wvu8y/vUQm2Oa/l9yd/yUDd5ru00cjC7EKEJnTFaG3Oy71MP9VJpNY5wown+0ybFM1qh+6v1MroA9/eqT26RFvHGpBgLDM=
  app: italkiclone
  on: main

