jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "F0braCbvcTFB31weY4Hz+4eVMZsDiwqetD0vp503tCruNT++5TRBJRAv/BfLfuIljbGnLstJyBpsRxP9NNzScQTuCoH9cO0vbHl/WDLsS5NmZoGO+6xkrU/wY4cSsVwn3+zetWNkKMYMyF9diuUys5AwCoJCCdmjd25LKddtP76im3WjZ9dbpYzzPfNGrX+mlDCkkxy3Vcau1RBUatRAtnD5YDd622ajh/lSrOv0qxjTa68FH+0zoWzAvZWGsKcRzUJriFN3dLW/mJKXjlsTgnljTij7EmmgU9xT9UlVNE7lflV0Lm9wnXN5HxYgRKHp8BQB47lfrw7gebWKMNMSvMS3k4P23MBtqfXIWIUfQ8t1BH4nRPwlkmfmKEJXvvkQx4khP4i1aj8ru5QtXYOW4H3SYi3lwvT4BZ6+dx9GARNoHdtdZfwouWYEhA5aSUSpBD+E8euyWO8rreW80mu3AthvWKEFNSr7XSEGj3JbJleARHvIOsZfjgsLPiQ7JT6pF84QygYgGEXb8pNCo5li8/9BRf9KJphH9RwTPs9LQqEenljCSwcgD6g/qv4oN98j7W/Ugxp9j39bQXMpP2ocGLjsyyhnhjTvNhYJMRvHoYQW+tQPlI7W3fNefr+/n+nw4W6nRl9e9EiNkRCugX87ZG9uMtPppWoa5eucZpAIcIQ="
  app: languagelearningappbackend
  on: main

