jobs:
  include:
  - language: node_js
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "XIRNI8Uvt6EpJQdHackAHacnP862JXPGCgrJu+HkX8hsI1wy+LYPunqZQcty6S8mCNea7E+GP+Mnnh9fhfDkiM9SBwNl3KKKpQM+amUk9kANzc/rz7WJxMcn52rryexcwB67HJdEDqM0wjTH3VY1ojMDVx7jl6hUDYb7woXjImPHiqqdqO9DvDK+dZuqgxjX+AaH3MAnM5AO8m2HePCHGgxyG3n6Nr2qNxv2A5jC5S1HwMZ7pg3gWGpAZX/7KjM7XqVRRjggGptYoob2GBYIL5ELubq+mhqmO6ndQfxERlqfJsluBYxI+gDTT1DgUTIwgBO5/nFxEhZD2owgqu1zei89gk0j7xYl72+sAJ9WjSzKwaDS1i43G+BmFTaQ85QHCLiyeagHgZUtHuAO9IUvuK0jPcbqc8KASc4kEsEGdPX4xX3/Agyt0y+uac58Kdt2c/TaGafwxhv47J4M/YX5RIhD+AQC+US6kZ0onhYP931g/46nZBVCYsGeNNLzv5rAwZiM/01C/6FtjGGrAQsdKlDYdnBasL2z4yA+HAYRx1C6ZyR1BFOLWiWsjLG9GyTTi6Up0TT6KJj8YX8yjtlTjlsA9Myfc0iqf/tU2BY/slMPGAFRQzK0VKbAy5T22VTaO5p2okcVHlkITBWTdOUwNLMgw9b5LE2HExo/q8j8Lrs="
      on: main