jobs:
  include:

  - language: node_js
    node_js: node
    cache:
      directories:
        - node_modules
    before_install: cd backend
    after_success: npm build
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
         secure: DwLtMqCyTgFLFvdlGbFS569ThlGm0LoHDkPVkin4ECxg+6vxvgbpJNeRKmUdc3y7bVC6TUD3n9on1ugvTgXr+l50gn0XNUgxQYIDD8F5PCfVN3LJLUlrUqU59kt8Z+/emQZoSu3uBtB7oXQFiHjTATNxmWxVYougNTq4nNrjwFNUNCn2xaowgPwfRy3DRS/1QB0sAKkNEjlC5xLkMjDlRmw6Y4zKxxGoernq+CvMhEyP+6iqtRu/hd/MA0uUwgmuldsgcRVEaG3VKsLRWDL9JjyHQBsqc5Jqyx0jCdTMkbGbG695AkolsMDBE2Nelq3xrjJQ7kIHyV22IHJYsLN6ln3ij8U2Ft4OLcitHZuHpK6U2QHgdPhR7Xzk/eS0Bu2rGELZ81ITqK8AIKCgpaa2Cr+/FcdgXw86BX7Td5XhL/Wm1EDaGxQXf2pHaMkGh4vJ0y3S88yEqTBRKjuJOGAJzIdSI2ka1pUXXR4Pi6br4NLfkALKVJ9KkmJLTQqhHyf7hBLvew/UOAdzvaB9FR/CM68vB2wVvPTMA6GI6KSee2NbaV/YQP0fmJM+W+AthAauSYKjuFEXYIZWoVPaxJsvxEPFy5bc61xPzVmKj8kNJ4lh/lNVCP0spUgEGDI+THxp7P74hC7dnjgFPz7elHVRUbpCpJkLZxaI9bLwjXKakkQ=
      app: languagelearningapp
      on: main

  - language: node_js

    dist: trusty
    
    before_install: cd backend
    cache:
      directories:
        - node_modules

    addons:
      chrome: stable

    script:
      - npm run test:headless
      - npm run build
      
    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
         secure: DwLtMqCyTgFLFvdlGbFS569ThlGm0LoHDkPVkin4ECxg+6vxvgbpJNeRKmUdc3y7bVC6TUD3n9on1ugvTgXr+l50gn0XNUgxQYIDD8F5PCfVN3LJLUlrUqU59kt8Z+/emQZoSu3uBtB7oXQFiHjTATNxmWxVYougNTq4nNrjwFNUNCn2xaowgPwfRy3DRS/1QB0sAKkNEjlC5xLkMjDlRmw6Y4zKxxGoernq+CvMhEyP+6iqtRu/hd/MA0uUwgmuldsgcRVEaG3VKsLRWDL9JjyHQBsqc5Jqyx0jCdTMkbGbG695AkolsMDBE2Nelq3xrjJQ7kIHyV22IHJYsLN6ln3ij8U2Ft4OLcitHZuHpK6U2QHgdPhR7Xzk/eS0Bu2rGELZ81ITqK8AIKCgpaa2Cr+/FcdgXw86BX7Td5XhL/Wm1EDaGxQXf2pHaMkGh4vJ0y3S88yEqTBRKjuJOGAJzIdSI2ka1pUXXR4Pi6br4NLfkALKVJ9KkmJLTQqhHyf7hBLvew/UOAdzvaB9FR/CM68vB2wVvPTMA6GI6KSee2NbaV/YQP0fmJM+W+AthAauSYKjuFEXYIZWoVPaxJsvxEPFy5bc61xPzVmKj8kNJ4lh/lNVCP0spUgEGDI+THxp7P74hC7dnjgFPz7elHVRUbpCpJkLZxaI9bLwjXKakkQ=
      app: languagelearningfrontend
      on: main