jobs:
  include:
  - language: node_js
    before_install: cd backend
    node_js: node
    cache:
      directories:
      - node_modules
    after_success: npm build
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: WCEspp6lKLe/hS1ZKcpuW7X1BcrriCux3lwXu4R+GInMiiu2KkDfGYscWHAPVLFJwvNNdsILJnYFchueGyxfChGrEw2Lb4eWrpDphW2cMF6GeYrt2R46hMAdbsI7tZvTDvde4rRFqCoEejSq9AaKFKBb1/Fdp/uaJnNtQIT0qRzIOLLnTDS1t45ymQtTzGZF0n/Ni6PhkkJOcqOrn1LnHSq4ZVZotYb0oh47NxuQ/czkLT45BFJ+SbbDppFt2CZj5ZyhzUDD+3mct7PaxJOXSOL85eX5x4AXbBd7PQCflkGB5sjDjwR2N9D7u/OUlewJ80fEhwf9D91j9sUL6wzRRPGVv92toEz5nXVH1YtnAuZqr5SMftW4TNOhMDsX1vJaDRytpxR8QLSHvaTomLbTPb9PUpkX49YTh/PYmvSvc78EZ5L3IJ7FHWLpqKaTX58XdKBpNxDUKdMLqSxl/xXEpz8evIfI0tVQlg+DKqaExplue3eHtioInj0gkhQrD0FIJwJKm10o1E2e7r+jlIQM6qaidIdYPgFWpMIq1oyUq0U8NbjU0IA8TltSTzDiotLyoUAvBwP99cLSBKueQMwGIEUW+DCgHgtMqhUxvPxZf1CkiD+3wltYdAkkBfC4Nm1s7baJ6ytLJ5LItgYWqNyTcqMVLMnMufv5yqRSnngMhNE=
    app: languagelearningapp
  on: main

